/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ministry;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class AddPharmacist extends javax.swing.JFrame {

    /**
     * Creates new form AddPharmacist
     */
    public AddPharmacist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblPharmacistName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtPharmacistName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnArrow = new javax.swing.JButton();
        lblPharmacyName = new javax.swing.JLabel();
        txtPharmacyName = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPharmacistName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPharmacistName.setText("pharmacist name");
        jPanel1.add(lblPharmacistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 130, -1));

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        txtPharmacistName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtPharmacistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, -1));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        txtPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 120, -1));

        btnArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.jpeg"))); // NOI18N
        btnArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lblPharmacyName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPharmacyName.setText("Pharmacy name");
        jPanel1.add(lblPharmacyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtPharmacyName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPharmacyName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtPharmacyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, -1));

        lblAdress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblAdress.setText("Adress");
        jPanel1.add(lblAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        txtAdress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 140, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 239, 90, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ministryOfHealthLogoBackground.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 430, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrowActionPerformed
        if(AdminSession.isLoggedIn()){
            setVisible(false);
            new HeadHome().setVisible(true);
        }else {
            // Redirect to adminLogin.java
            setVisible(false);
            AdminSession.setLoggedIn(false,-1); // Reset isLoggedIn status
            new ministryLogin().setVisible(true);
        }
    }//GEN-LAST:event_btnArrowActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String pharmacistName= txtPharmacistName.getText();
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        String pharmacyName = txtPharmacyName.getText();
        String pharmacyAdress = txtAdress.getText();
        int adminId = AdminSession.getMinistryAdminId();
        
        try{
            
            Connection conn;
            Statement st;
            ResultSet rs;
            PreparedStatement ps;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            
            String insertToAdmin = "INSERT INTO admin (name,email,pass,ministry_id) VALUES (?,?,?,?)";
            ps = conn.prepareStatement(insertToAdmin);
            ps.setString(1,pharmacistName);
            ps.setString(2,email);
            ps.setString(3,password);
            ps.setInt(4, adminId);
            ps.executeUpdate();
            System.out.println("Data inserted successfully into admin.");
            
            rs = st.executeQuery("SELECT id From admin WHERE email='"+email+"'");
            int pharmacistId = -1;
            if(rs.next()){
                pharmacistId = rs.getInt(1);
            }
            if(pharmacistId>0){
                String insertToPharma = "INSERT INTO pharma (address,phName,admin_id) VALUES (?,?,?)";
                ps = conn.prepareStatement(insertToPharma);
                ps.setString(1, pharmacyAdress);
                ps.setString(2, pharmacyName);
                ps.setInt(3, pharmacistId);
                ps.executeUpdate();
                System.out.println("Data inserted successfully into pharma.");
            }else{
                JOptionPane.showMessageDialog(null,"no pharmacist to add pharmacy", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPharmacist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnArrow;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPharmacistName;
    private javax.swing.JLabel lblPharmacyName;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPharmacistName;
    private javax.swing.JTextField txtPharmacyName;
    // End of variables declaration//GEN-END:variables
}
