/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ministry;



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class updatePharmacist extends javax.swing.JFrame {

    /**
     * Creates new form updatePharmacist
     */
    public updatePharmacist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblNewAdress = new javax.swing.JLabel();
        txtNewAdress = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();
        btnArrow = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNewAdress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblNewAdress.setText("Enter the new adress");
        jPanel1.add(lblNewAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, 30));

        txtNewAdress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNewAdress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNewAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewAdressActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 200, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnUpdate.setText("Save");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 80, 30));

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 200, 30));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblName.setText("Pharmacist name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 78, -1, 30));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 82, 200, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ministryOfHealthLogoBackground.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        btnArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.jpeg"))); // NOI18N
        btnArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (AdminSession.isLoggedIn()) {
        
            String email = txtEmail.getText();
            String adress = txtNewAdress.getText();
            String name = txtName.getText();
            String testName= null;
            String testEmail = null;

            try{

                Connection conn;
                Statement st;
                ResultSet rs;
                conn = connectdb.createconnection();
                st = conn.createStatement();

                rs = st.executeQuery("SELECT name,email FROM admin WHERE name='"+name+"' AND email='"+email+"'");

                if(rs.next()){

                    testName = rs.getString(1);
                    testEmail = rs.getString(2);
                }
                if(email.equals(testEmail) && name.equals(testName)){
                    st.executeUpdate("UPDATE pharma INNER JOIN admin on admin.id=pharma.admin_id SET address='"+adress+"' WHERE admin.email='"+email+"' AND admin.name='"+name+"' ");
                    System.out.println("pharma updated");
                }else{
                    JOptionPane.showMessageDialog(null,"name or email doesn't exist please check them. ", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                setVisible(false);
                new updatePharmacist().setVisible(true);
            } catch (SQLException sqlException) {
                // Handle SQLException
                sqlException.printStackTrace();
            } catch (Exception generalException) {
                // Handle other exceptions (general case)
                generalException.printStackTrace();
            }
        } else {
            // Redirect to adminLogin.java
            setVisible(false);
            AdminSession.setLoggedIn(false,-1); // Reset isLoggedIn status
            new ministryLogin().setVisible(true);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNewAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewAdressActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrowActionPerformed
        if(AdminSession.isLoggedIn()){
            setVisible(false);
            new HeadHome().setVisible(true);
        }else {
            // Redirect to adminLogin.java
            setVisible(false);
            AdminSession.setLoggedIn(false,-1); // Reset isLoggedIn status
            new ministryLogin().setVisible(true);
        }
        
    }//GEN-LAST:event_btnArrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatePharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatePharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatePharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatePharmacist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatePharmacist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewAdress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewAdress;
    // End of variables declaration//GEN-END:variables
}
